"""add test_case_image_url to shl_solver_history

Revision ID: 23189c7092ff
Revises: af0c96dc672c
Create Date: 2026-05-14 00:20:10.938244

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "23189c7092ff"
down_revision: Union[str, Sequence[str], None] = "af0c96dc672c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shl_solver_history",
        sa.Column("test_case_image_url", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shl_solver_history", "test_case_image_url")
    # ### end Alembic commands ###
