"""alter token_record field

Revision ID: 403dea7909f5
Revises: 69927bca59d6
Create Date: 2026-02-21 11:59:46.653405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '403dea7909f5'
down_revision: Union[str, Sequence[str], None] = '69927bca59d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_record', sa.Column('model', sa.String(length=100), nullable=True))
    op.drop_index(op.f('ix_token_record_ip'), table_name='token_record')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_token_record_ip'), 'token_record', ['ip'], unique=False)
    op.drop_column('token_record', 'model')
    # ### end Alembic commands ###
