"""add user_id field

Revision ID: 521200355f5e
Revises: 403dea7909f5
Create Date: 2026-02-22 18:15:35.986981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '521200355f5e'
down_revision: Union[str, Sequence[str], None] = '403dea7909f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_record', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_record', 'user_id')
    # ### end Alembic commands ###
