"""add token_record table

Revision ID: 69927bca59d6
Revises: 46dab5102919
Create Date: 2026-02-21 11:36:44.607204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69927bca59d6'
down_revision: Union[str, Sequence[str], None] = '46dab5102919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_record',
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_record_id'), 'token_record', ['id'], unique=False)
    op.create_index(op.f('ix_token_record_ip'), 'token_record', ['ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_record_ip'), table_name='token_record')
    op.drop_index(op.f('ix_token_record_id'), table_name='token_record')
    op.drop_table('token_record')
    # ### end Alembic commands ###
