"""add shl_solver_history table

Revision ID: e0267ad67cb1
Revises: b6bd61c5f2e3
Create Date: 2026-03-11 20:52:25.273091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0267ad67cb1'
down_revision: Union[str, Sequence[str], None] = 'b6bd61c5f2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
