"""add test_case_image_url to shl_solver_history

Revision ID: e6560f995b1b
Revises: 23189c7092ff
Create Date: 2026-05-14 00:46:39.393814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6560f995b1b'
down_revision: Union[str, Sequence[str], None] = '23189c7092ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shl_solver_history', sa.Column('test_case_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shl_solver_history', 'test_case_image_url')
    # ### end Alembic commands ###
